[tool.poetry]
name = "trainingproject"
version = "0.1.0"
description = ""
authors = ["micheleone99 <romaniuk@wa.onet.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
